### ISSUE TITLE
Failed to interpolate MODIS Chlorophyll-a Data

### ISSUE THREAD

**Issue by hidayatmn378** [gher-uliege/DINCAE#14]
**Describe the bug**

A description of what the bug is.

**To Reproduce**

Please provide a minimal code example which reproduces the behavior (bug, performance regression, ...).

**Environment**

 - operating system: Ubuntu 16.04.7 LTS
 - Python version 3.7.12
 - Tensorflow version 1.15.0 
 - DINCAE version  v1.1.0 (Latest)

**Full output**

In case of an error, please paste the full error message and stack trace.
The file output attached [record_modis_chl_3d.txt](https://github.com/gher-uliege/DINCAE/files/10609966/record_modis_chl_3d.txt)

**Input file**

Run the shell command `ncdump -h myfile.nc` and paste the output here.
`netcdf input_file_python {
dimensions:
	lon = 445 ;
	lat = 459 ;
	time = UNLIMITED ; // (3 currently)
variables:
	float lon(lon) ;
	float lat(lat) ;
	float time(time) ;
		time:units = "days since 2021-01-01 00:00:00" ;
	float chl(time, lat, lon) ;
		chl:_FillValue = -9999.f ;
	int mask(lat, lon) ;
		mask:comment = "one means the data location is valid (e.g. sea for SST), zero the location is invalid (e.g. land for SST)" ;

// global attributes:
		:_NCProperties = "version=2,netcdf=4.8.1,hdf5=1.12.2" ;
}`

**Comment by jsihunh** [comment]
Hello, your error was come from shortage of GPU capacity. i recommend to reduce your study area because your data dimension( lat(459 pixels) and lon(445 pixels)) was too large as input data in deep learning lat(459 pixels) and lon(445 pixels).

**Comment by hidayatmn378** [comment]
Thank you for your help. Now it works...
